name: recipe
description: sample project
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1

  cupertino_icons: ^1.0.6
  go_router: ^12.1.1
  responsive_framework: ^1.1.1
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  retrofit: ^4.0.3
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  freezed: ^2.4.5
  build_runner: ^2.4.6
  retrofit_generator: ^8.0.4
  json_serializable: ^6.7.1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
          style: normal
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 700
          style: normal

flutter_intl:
  enabled: true
  class_name: S